In [1]:
import pandas as pd

In [3]:
#read the file

df = pd.read_excel('wc_event_data.xlsx')

In [5]:
# show data

df.head()

,id,index,period,timestamp,minute,second,possession,duration,type_id,type_name,...,goalkeeper_punched_out,block_save_block,shot_saved_to_post,goalkeeper_shot_saved_to_post,half_start_late_video_start,shot_saved_off_target,goalkeeper_shot_saved_off_target,goalkeeper_success_in_play,shot_redirect,goalkeeper_lost_in_play
0,093f898d-33b1-4425-b591-37dd9c9bf70b,1,1,00:00:00,0,0,1,0.000000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,79a9efbb-b5e5-45b0-983d-8729bcc4a0e1,2,1,00:00:00,0,0,1,0.000000,35,Starting XI,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,c4cdfc71-b9f4-4751-a714-e816c1419457,3,1,00:00:00,0,0,1,0.000000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,51f295b8-da96-428e-ab47-90f380f8cf53,4,1,00:00:00,0,0,1,0.000000,18,Half Start,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4acb4fd2-f46a-4d73-993c-e06597873924,5,1,00:00:00.521000,0,0,2,1.220932,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df.columns

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'possession',
       'duration', 'type_id', 'type_name',
       ...
       'goalkeeper_punched_out', 'block_save_block', 'shot_saved_to_post',
       'goalkeeper_shot_saved_to_post', 'half_start_late_video_start',
       'shot_saved_off_target', 'goalkeeper_shot_saved_off_target',
       'goalkeeper_success_in_play', 'shot_redirect',
       'goalkeeper_lost_in_play'],
      dtype='object', length=142)

In [20]:
# show all players where they have center forward position under the position_name column
new_df = df[df['position_name'] == 'Center Forward']

new_df.head()

,id,index,period,timestamp,minute,second,possession,duration,type_id,type_name,...,goalkeeper_punched_out,block_save_block,shot_saved_to_post,goalkeeper_shot_saved_to_post,half_start_late_video_start,shot_saved_off_target,goalkeeper_shot_saved_off_target,goalkeeper_success_in_play,shot_redirect,goalkeeper_lost_in_play
4,4acb4fd2-f46a-4d73-993c-e06597873924,5,1,00:00:00.521000,0,0,2,1.220932,30,Pass,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,9199237f-2ffc-4a71-b15d-d928879dbb74,24,1,00:00:22.127000,0,22,2,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,aa77495b-0e7b-44f0-a2eb-11605085943a,25,1,00:00:22.129000,0,22,2,0.175803,16,Shot,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,1c327bce-b162-4270-8611-4f39b34829ff,42,1,00:00:51.771000,0,51,4,NaN,42,Ball Receipt*,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,e9fad88c-6795-4e10-93f0-edd6db302a68,43,1,00:00:51.771000,0,51,4,0.735769,43,Carry,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# show all players in the new_df created before where they have clearance, block, duel and interception 

new_df = new_df[new_df['type_name'].isin(['Clearance', 'Block', 'Duel', 'Interception'])]

new_df["player_name"]

474           Breel-Donald Embolo
1491          Breel-Donald Embolo
1608          Breel-Donald Embolo
2234          Breel-Donald Embolo
2606          Breel-Donald Embolo
                   ...
233279               Issam Jebali
233315               Issam Jebali
233357               Issam Jebali
234431    Andreas Evald Cornelius
234582      Taha Yassine Khenissi
Name: player_name, Length: 662, dtype: object

In [24]:
# show top players with the highest number of events

new_df["player_name"].value_counts().head(10)

Youssef En-Nesyri                    41
Olivier Giroud                       30
Harry Kane                           27
Issam Jebali                         26
Richarlison de Andrade               24
Robert Lewandowski                   22
Bruno PetkoviÃ„â€¡                      19
Daizen Maeda                         19
Gue-Sung Cho                         19
Michael Steveen Estrada MartÃƒÂ­nez    18
Name: player_name, dtype: int64

In [54]:
new1_df = df[df["pass_body_part_name"].isin(['Right Foot', 'Left Foot'])]
#for every player name find the number of passes done with the left foot and with the right foot. If the player has has made more passes with one foot than the other we just keep the one with the least passes completed.
new1_df.groupby(["player_name", "pass_body_part_name"]).size()
#rank the players based on the number of passes they have made with the least foot. From that number of passes with that foot, rank the players based on the most number of passes made
new1_df.groupby(["player_name", "pass_body_part_name"]).size().unstack().fillna(0).min(axis=1).sort_values(ascending=False)

player_name
Aymeric Laporte                 157.0
JoÃ…Â¡ko Gvardiol                 148.0
RaphaÃƒÂ«l Varane                 119.0
Ivan PeriÃ…Â¡iÃ„â€¡                  106.0
Rodrigo HernÃƒÂ¡ndez Cascante     101.0
                                ...
Marko GrujiÃ„â€¡                     0.0
DeAndre Yedlin                    0.0
Maximiliano GÃƒÂ³mez GonzÃƒÂ¡lez      0.0
Georges-KÃƒÂ©vin Nkoudou Mbida      0.0
Nasser Al Dawsari                 0.0
Length: 674, dtype: float64

In [35]:
# order new1_df by pass_body_part_name frequency in descending order, find the first player that appears twice

new2_df = new1_df.groupby(["player_name", "pass_body_part_name"]).size().sort_values(ascending=False)
new2_df

player_name                   pass_body_part_name
Rodrigo HernÃƒÂ¡ndez Cascante   Right Foot             549
Rodrigo Javier De Paul        Right Foot             524
Luka ModriÃ„â€¡                  Right Foot             480
NicolÃƒÂ¡s HernÃƒÂ¡n Otamendi     Right Foot             472
Marcelo BrozoviÃ„â€¡             Right Foot             431
                                                    ...
Ghilane Chalali               Left Foot                1
Gerson Torres Barrantes       Right Foot               1
Denis Lemi Zakaria Lako Lado  Left Foot                1
Bassam Hisham Al Rawi         Left Foot                1
Alireza Jahanbakhsh           Left Foot                1
Length: 1287, dtype: int64

('Mohammed Muntari', 'Left Foot')
('Vitor Machado Ferreira', 'Left Foot')
('Assim Omer Al Haj Madibo', 'Left Foot')
('Hassan Mohammed Al-Tambakti', 'Left Foot')
('Badr Banoun', 'Left Foot')
('Woo-Yeong Jeong', 'Left Foot')
('Harry Wilson', 'Right Foot')
('Abdullah Mohammed Madu', 'Right Foot')
('Niclas FÃƒÂ¼llkrug', 'Left Foot')
('Nader Ghandri', 'Left Foot')
('Exequiel Alejandro Palacios', 'Left Foot')
('Abderrazak Hamdallah', 'Left Foot')
('Noah Okafor', 'Left Foot')
('William Saliba', 'Left Foot')
('Wajdi Kechrida', 'Left Foot')
('Yuki Soma', 'Left Foot')
('Yahya Jabrane', 'Right Foot')
('Ikoma LoÃƒÂ¯s Openda', 'Left Foot')
('Abdessamad Ezzalzouli', 'Left Foot')
('Ederson Santana de Moraes', 'Right Foot')
('Filip MladenoviÃ„â€¡', 'Right Foot')
('Haris SeferoviÃ„â€¡', 'Right Foot')
('Hattan Babhir', 'Left Foot')
('Youssoufa Moukoko', 'Left Foot')
('Hannibal Mejbri', 'Right Foot')
('Ayase Ueda', 'Left Foot')
('Ardon Jashari', 'Right Foot')
('Roozbeh Cheshmi', 'Left Foot')
('Djorkaeff Neicer Reasco GonzÃƒÂ¡lez', 'Right Foot')
('Karim Ansarifard', 'Left Foot')
('MatÃƒ\xadas NicolÃƒÂ¡s ViÃƒÂ±a Susperreguy', 'Right Foot')
('Darko LazoviÃ„â€¡', 'Left Foot')
('Jordan Ayew', 'Left Foot')
('Takefusa Kubo', 'Right Foot')
('Taha Yassine Khenissi', 'Right Foot')
('Daniel James', 'Left Foot')
('JosÃƒÂ© AndrÃƒÂ©s Guardado HernÃƒÂ¡ndez', 'Right Foot')
('Stephen Antunes EustÃƒÂ¡quio', 'Left Foot')
('Kalvin Phillips', 'Left Foot')
('Shaquell Moore', 'Left Foot')
('Nicolas Moumi Ngamaleu', 'Left Foot')
('Mehdi Torabi', 'Left Foot')
('Callum Wilson', 'Left Foot')
('Carlos Alberto RodrÃƒ\xadguez GÃƒÂ³mez', 'Left Foot')
('AndrÃƒÂ© Miguel Valente Silva', 'Left Foot')
('Christian Mougang Bassogog', 'Right Foot')
('Carlos Manuel MartÃƒ\xadnez Castro', 'Left Foot')
('AndrÃƒÂ© Ayew PelÃƒÂ©', 'Right Foot')
('Luka JoviÃ„â€¡', 'Left Foot')
('Cheikhou KouyatÃƒÂ©', 'Left Foot')
('Sadegh Moharrami', 'Left Foot')
('Saad Abdullah Al Sheeb', 'Left Foot')
('Brandon Aguilera Zamora', 'Right Foot')
('Juan Marcos Foyth', 'Right Foot')
('Karim Ansarifard', 'Right Foot')
('Devis Rogers Epassy Mboka', 'Left Foot')
('Antoine Semenyo', 'Right Foot')
('Alan Steven Franco Palma', 'Left Foot')
('Jerome Ngom Mbekeli', 'Right Foot')
('Jesus Ferreira', 'Left Foot')
('Facundo Pellistri Rebollo', 'Left Foot')
('Ahmed Alaa Eldin Abdelmotaal', 'Right Foot')
('Jewison Bennette', 'Right Foot')
('Jamie MacLaren', 'Left Foot')